### ISSUE TITLE
can't adjust the size of the video display

### ISSUE THREAD

**Issue by fredjoe7** [midrare/anki-video#1]
the video plays in full screen and cant seems to adjust the size

**Comment by midrare** [comment]
What OS are you on? What other plugins installed? Is this happening in the card editor or the reviewer? Can you post a screenshot?

**Comment by fredjoe7** [comment]
windows 11. 
it happens in reviewer only.. 
Anki 23.10.1
i disabled all addons and tried with only this addon on.
![image](https://github.com/midrare/anki-video/assets/107930196/8ef277f7-ec5c-4dff-a67d-2f7992230be2)
![image](https://github.com/midrare/anki-video/assets/107930196/f861633e-da73-4b5a-a604-4ba4b097e921)
![image](https://github.com/midrare/anki-video/assets/107930196/86a54c05-b54e-4b12-886a-9b080d9893bf)
![image](https://github.com/midrare/anki-video/assets/107930196/62ba7909-0f04-4489-abbe-ff9a47f2892b)

**Comment by fredjoe7** [comment]
adding the video inline using this addon and then disabling the addon seems to make the video play in normal size in reviewer...
![image](https://github.com/midrare/anki-video/assets/107930196/0fb7ea17-fc44-43d8-b864-1e19e41283ff)

**Comment by midrare** [comment]
Did you try scrolling down in the reviewer window?

**Comment by fredjoe7** [comment]
scrolling works fine... just that there is no way to make it small... probably have to add some codes in the styling for  scaling... like max width or max height

**Comment by fredjoe7** [comment]
but i dont understand why it scales properly after disabling the addon and looks zoomed up with addon enabled

**Comment by fredjoe7** [comment]
the buttons in the bottom right are not clickable also
![image](https://github.com/midrare/anki-video/assets/107930196/6a5b202a-6778-45c9-be83-6824f56c1b61)

**Comment by midrare** [comment]
Try the attached addon. Go to addon config, click "restore defaults", then set `size` to `720x480`. Restart Anki and see if the video size is what you set it to.

[anki-video-dev.zip](https://github.com/midrare/anki-video/files/13540414/anki-video-dev.zip)

**Comment by fredjoe7** [comment]
that works.

i feel the ability to adjust the size for individual videos right from the editor or browser  (just like what we do for images) will be more user friendly.

right now if i set auto, it remains inappropriately enlarged.

if i set to 720x480 , then every video will be of the same size...(cannot individualize for each video) .

**Comment by midrare** [comment]
You can already do that. Just click the `</>` button and find the `<video>` element. There should be a bunch of `<config>` elements whose value you can set.

**Comment by fredjoe7** [comment]
![image](https://github.com/midrare/anki-video/assets/107930196/0788269a-2fbc-4ac7-899c-f850c766e0a3)

not sure if size is mentioned here

**Comment by fredjoe7** [comment]
![image](https://github.com/midrare/anki-video/assets/107930196/a57f094f-cabb-4828-b5f3-9c9985bbc7a2)
had to manually add it ...

can you make the addon to automatically add that parameter ?

**Comment by midrare** [comment]
The newest version should have it as a `<config>`. You'll need to re-insert the video for it to show. Don't use the attributes, they'll cause issues when merging with global config.

**Comment by midrare** [comment]
Closing now, comment if you still have issues.
