### ISSUE TITLE
Interferes with normal pasting of text (or anything) into anki cards...

### ISSUE THREAD

**Issue by fredjoe7** [midrare/anki-video#2]
With this addon enabled,

 i cannot use control + V shortcut to paste text or anything  
 
 also i tried pasting texts from clipboard that doesnot work...

(tried with only this addon enabled)  

 disabling the addon solved the issues..

**Comment by midrare** [comment]
Ok. Try this. Install it from the "Install from file..." button in the addons pane and tell me if the problem is fixed.

[anki-video-dev.zip](https://github.com/midrare/anki-video/files/13540011/anki-video-dev.zip)

**Comment by fredjoe7** [comment]
tried with this.... no more issues in pasting...

**Comment by fredjoe7** [comment]
works normally if using only this addon ...

but if i use it with my regular addons , it starts like this
![image](https://github.com/midrare/anki-video/assets/107930196/cc789116-a214-4a95-9da1-802557ad531d)

then when i click the decks , its turning back normally... 
list of my addons enabled
![image](https://github.com/midrare/anki-video/assets/107930196/46457a1a-506b-4e38-adb5-7ec3dc9d9c8b)

**Comment by midrare** [comment]
Try disabling addons until you find which one is causing the interference.

**Comment by fredjoe7** [comment]
i tried disabling the ankivideo and it still persisted... its probably causedf by someother addon
